# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: HolyPHP.HolyPHP
PackageVersion: 1.0.1
PackageLocale: en-US
Publisher: HolyPHP
PublisherUrl: https://hphp.ch/
PackageName: HolyPHP
PackageUrl: https://hphp.ch/
License: MIT
LicenseUrl: https://github.com/Elifoxcoder/holyphp/blob/main/LICENSE
ShortDescription: Compile HolyPHP programs into standalone native executables.
Moniker: hphp
Tags:
- cli
- command-line
- compiler
- developer-tools
- programming
- shell
- utilities
ManifestType: defaultLocale
ManifestVersion: 1.9.0
